### PR TITLE
Fixed remaining arguments bug.

### PR DESCRIPTION
**Pull request by patriksvensson**

### CODE REVIEW

**Comment by hal-ler** [comment]
Does this fix work for you guys? I still get the same error as before.
I tried removing "Verbose" and "$Verbose.IsPresent" and it still yields the expected behavior for "VerbosePreference" (set to continue if "-Verbose" is present on the command line).

**Comment by patriksvensson** [comment]
@hal-ler I'm not sure what you mean to be honest. I might be missing some context here.

**Comment by hal-ler** [comment]
Running:

`Invoke-WebRequest http://cakebuild.net/bootstrapper/windows -OutFile cake-bootstrap.ps1
.\cake-bootstrap.ps1`

Yields:

`<position> : A parameter with the name 'Verbose' was defined multiple times for the command.`

If I remove:

`[switch]$Verbose,`

and

`# Should we show verbose messages?
if($Verbose.IsPresent)
{
    $VerbosePreference = "continue"
}`

then it works. The option "-Verbose" also works and sets "VerbosePreference" to "continue" implicitly.

**Comment by patriksvensson** [comment]
@hal-ler Ah, strange, I cannot reproduce that here for some reason.

There is no `[CmdletBinding()]` in that file so that should not occur. Can you verify that your bootstrapper looks exactly as the one at [http://cakebuild.net/bootstrapper/windows](http://cakebuild.net/bootstrapper/windows).

**Comment by hal-ler** [comment]
@patriksvensson Copy pasted the content of the link to a local file to make sure that I am running the right version and I still get the same behavior. Could it be the Windows version? I am running Windows 10.

**Comment by patriksvensson** [comment]
@hal-ler No, I don't think so. I'm running Windows 10 as well. I need to sleep now (it's 00:20 AM here), but I'll take a look at it hopefully tomorrow.

**Comment by hal-ler** [comment]
@patriksvensson Reading through powershell documentation: "but to be recognized as
      an advanced function (rather than a simple function), a function must have
      either the CmdletBinding attribute or the Parameter attribute, or both." https://technet.microsoft.com/library/hh847743.aspx

**Pull request merged**
